version: '3'

services:
  redis:
    container_name: redis
    image: redislabs/rejson
    command: redis-server
    restart: always

  bot:
    container_name: bot
    depends_on:
      - redis
    build: .
    restart: always
